---
- name: copy systemd files to master
  template: src={{role_path}}/templates/{{item}} dest=/var/lib/yaml/
  with_items:
    - "heapster.yaml"
 
- name: copy init file
  copy: src={{role_path}}/files/init.sh dest=/var/lib/yaml/init.sh mode=755

- name: run snap   
  shell: /var/lib/yaml/init.sh http://127.0.0.1:8080

  
