apiVersion: v1
clusters:
- cluster:
    server: http://{{nginx_ip_address}}:{{nginx_port}}
  name: local
contexts:
- context:
    cluster: local
    user: kubelet
  name: kubelet-context
current-context: kubelet-context
kind: Config
preferences: {}
users:
- name: kubelet
