---
- name: Set IP address variables
  set_fact:
    master_ip_address: "{{groups['masters'][0]}}"
    node_ip_address: "{{ hostvars[groups['nodes'][0]]['ansible_default_ipv4']['address'] }}"
    etcd_ip_address: "{{ hostvars[groups['etcd'][0]]['ansible_default_ipv4']['address'] }}"
    board_ip_address: "{{ hostvars[groups['board'][0]]['ansible_default_ipv4']['address'] }}"
    nsf_server_ip_address: "{{ hostvars[groups['nfs-server'][0]]['ansible_default_ipv4']['address'] }}"
    registry_ip_address: "{{groups['nfs-server'][0]}}"

