---
- copy: 
    src: "{{role_path}}/files/docker-ce.repo"
    dest: /etc/yum.repos.d/
    owner: root
    group: root
- copy:
    src: "{{role_path}}/files/selinuxConfig"
    dest: /etc/selinux/config
- name: stop the firewall
  shell: systemctl stop firewalld.service
  ignore_errors: yes
- name: stop the firewall
  shell: systemctl disable firewalld.service
  ignore_errors: yes
- name: set enforce 0
  shell: set enforce 0
  ignore_errors: yes


- name: create directory to save rpm package
  shell: mkdir -p /tmp/rpm
- name: copy docker-ce rpm package
  copy: src={{role_path}}/../../pre-env/docker-ce dest=/tmp/rpm

