---
- name: copy yaml file
  template: src={{role_path}}/templates/calico.yaml dest=/var/lib/yaml/ mode=755

- name: copy init file
  copy: src={{role_path}}/files/init.sh dest=/var/lib/yaml/init.sh mode=755

- name: kubectl create calico
  shell: /var/lib/yaml/init.sh http://{{master_ip_address}}:8080


  
