---
- name: install docker-ce
  yum: name=docker-ce state=latest

- name: copy modify docker script
  template: src={{role_path}}/templates/sed.sh dest=/etc mode=755
- name: modify docker config file
  shell: /etc/sed.sh

- name: start docker
  service: name=docker enabled=yes state=started

- name: config daemon.json file
  copy: src={{role_path}}/files/daemon.json dest=/etc/docker/daemon.json

- name: restart docker
  service: name=docker enabled=yes state=restarted

